### ISSUE TITLE
Mia Grodsky - Scribble

### ISSUE THREAD

**Issue by mcgrodsky** [ga-dc/scribble#108]
GitHub Repo - https://github.com/mcgrodsky/scribble

Heroku Deployment - https://the-swift-sorcerer.herokuapp.com/posts

Comfort - 3/5 - I really enjoyed this project and had a lot of fun with rails. I feel like everything we learned over the past 2 weeks came together in creating this blog, and i learned a TON about rails.

Complete - 3/5 - I filled all of the requirements, but I am not sure if my user authentication is working as it's supposed to. One thing that i couldn't figure out was after i deployed my site to Heroku, my background image (still in css) wouldn't show up (everything else worked fine and was committed/pushed at the same time- thinking its maybe because i stole it off the internet and Heroku could tell or something?)

**Comment by jshawl** [comment]
:+1: Looks great - here's my code feedback https://github.com/mcgrodsky/scribble/compare/master...jesseshawl:master

re: your background image, looks like the url is wrong https://the-swift-sorcerer.herokuapp.com/assets/dessert.jpg 

consider using `asset_path` here https://github.com/mcgrodsky/scribble/blob/4f304ada4710356198d124114e3f3367c27fba92/app/assets/stylesheets/application.css#L21
