### ISSUE TITLE
progress to date

### ISSUE THREAD

**Issue by ghost** [ga-dc/scribble#120]
A few things here. 
Worked my way through the tutorial again Wed night, asking and answering questions.  repo is https://github.com/thomhouseholder/blog1

Worked on it again tonight, using teachers/students instead of posts/comments.  repo is https://github.com/thomhouseholder/blog2.  Completed teacher model; still working on student model.  Deployed what I have so far: https://thom-blog2.herokuapp.com/teachers

My plan is to build Scribble this weekend to get back on track.

**Comment by jshawl** [comment]
:+1: Your code looks great thom! When possible, avoid using `rails g scaffold` https://github.com/thomhouseholder/blog2/blob/96b48884e779c27d27ba8a2c4339adbe706ddc8d/app/views/teachers/index.html.erb#L7

to get the extra practice in. Also, I took a look through your two repos, but did not see any questions - If i missed them, please point them out for me and I'd be happy to answer them.

Also happy to pair sometime this week and go over any concepts - but your teacher/student adaptation of the rails tutorial looks great!!

**Comment by ghost** [comment]
Is it possible that some code I wrote looks like it was created using a
scaffold?  I'm trying to steer clear of using scaffolds so I can learn.

I am working on Scribble and will add my questions to that Repo.
Frustrated trying to create comments that tie to posts.  Continue to run
into trouble trying to add comments to my posts.  I'm going to push to to
the repo and spend some time thinking about my project, then come back to
this.
