### ISSUE TITLE
Homework submission friday

### ISSUE THREAD

**Issue by Cajam** [ga-dc/scribble#128]
https://github.com/Cajam/scribble

**Comment by jshawl** [comment]
:+1: Looks great! I left code comments on two commits:

https://github.com/Cajam/scribble/commit/7410ae5dc81227e772a1f098022dc7c6b1691d23
and
https://github.com/Cajam/scribble/commit/9bbe716e80000e14473b02f91c02a0b56b86bf40

I'd like to see you implement user authentication and deploy this app to heroku - Let me know if you'd like to do this together sometime this week.
