### ISSUE TITLE
scribble 

### ISSUE THREAD

**Issue by mosesadg** [ga-dc/scribble#13]
comfort: 3
completeness:4

https://wdi-dc6-anand-scribble.herokuapp.com/sign_in
repo: https://github.com/mosesadg/scribble

**Comment by jshawl** [comment]
:+1: Excellent job on this assignment!!! I left code comments here - https://github.com/mosesadg/scribble/compare/master...jshawl:feedback

I would encourage you to research rails partials to dry up your code and reuse templates, but overall (again) great job! :star2:
