### ISSUE TITLE
Toni Langley Solution

### ISSUE THREAD

**Issue by tvcrawley** [ga-dc/scribble#147]
https://github.com/Chibiania/scribble

Complete: 5
Comfort: 4

Comment: At first, I didn't really understand what I was doing but then after reviewing the lectures, doing rails for zombies, and the hogwarts lab, I feel better about rails...not great but better.

**Comment by RobertAKARobin** [comment]
:white_check_mark: Better is good! Is there anything specific on which you'd like feedback?
