### ISSUE TITLE
Caitlin Solution

### ISSUE THREAD

**Issue by caitlindaitch** [ga-dc/scribble#151]
https://github.com/caitlindaitch/scribble

Comfort Level: 4.5
Completeness: 3.5

I was able to get a login functionality working but I definitely need to do a lot more styling to make it look OK. Also still need to adjust what displays when you're logged in or not logged in (remove the "new post" buttons, etc.), etc.

**Comment by beckybeauchamp1** [comment]
Hi Caitlin,

Great job on Scribble! Here is a link to my PR with comments that I left inline:
https://github.com/caitlindaitch/scribble/pull/1/files

Please let me know if you have any more questions!
