### ISSUE TITLE
Christine Movius Scribble App

### ISSUE THREAD

**Issue by christine-sm** [ga-dc/scribble#154]
Unsuccessful Attempt at Deploying It: https://scribble-0317.herokuapp.com/
My Code: https://github.com/cmmovius/scribble

Comfort: 4.5
Completion: 4.5

I really enjoyed building this from scratch! It is amazing to go from a simple ERD to a working application. I also had some fun implementing bootstrap and playing around with the styling once I got all of the functionality to work.

Next Steps:
- Add users and tags controllers
- Put in flash messages when user attempts to create an invalid post or comment
- Learn how to successfully deploy it on Heroku! I renamed my app to something more relevant before trying to deploy it... but that shouldn't be the culprit. So I'd love to walk through how to deploy it.

**Comment by beckybeauchamp1** [comment]
Hi Christine,

Great job on Scribble! Here is a link to my PR with additional comments inline:https://github.com/cmmovius/scribble/pull/1/files.

Also, to give you feedback on deployment, I left an inline comment in your Gemfile which was causing an error. Also, we are having a deployment lesson tomorrow which should help clarify everything. If you still have any further questions, please let me know!
