### ISSUE TITLE
Christine L's Blog

### ISSUE THREAD

**Issue by chrislovett03** [ga-dc/scribble#16]
https://newlovettblog.herokuapp.com/sign_in

**Comment by jshawl** [comment]
:+1: Remember to submit a link to your code as well in the future. I've left code comments here - https://github.com/christinelovett/NewScribble/compare/master...jshawl:feedback

Overall, nice job on this assignment! I like the user interface. I would encourage you to keep working on associating posts with a current user. Currently, users can type in any author name - which could be incriminating!
