### ISSUE TITLE
Phil's Blog

### ISSUE THREAD

**Issue by englep10** [ga-dc/scribble#17]
Finished the Blog!
Completeness 4
Comfort 4

https://phils-blog-scribble.herokuapp.com/

**Comment by andrewsunglaekim** [comment]
could you please push your code to a repository and link to it?

**Comment by andrewsunglaekim** [comment]
I would definitely recommend taking some time to finishing this code. You still need edit functionality for posts and full CRUD for commenting. Additionally it would be cool to start thinking about how your would involve the user authentication.
