### ISSUE TITLE
Yun Solution

### ISSUE THREAD

**Issue by hh747hh** [ga-dc/scribble#176]
https://github.com/hh747hh/Scribble

Post shows
Comments show (not contents)

**Comment by RobertAKARobin** [comment]
:white_check_mark: 

Is there anything specific on which you'd like feedback?

**Comment by hh747hh** [comment]
I just didn't have enough time to figure out everything.

I was stuck on the comment part. It was just showing as dot instead of
actual comment.(maybe will figure it out by doing project)

Woo Yun
