### ISSUE TITLE
Scribble

### ISSUE THREAD

**Issue by lanakushnir** [ga-dc/scribble#18]
comfort 4/5
complete 5/5

github link https://github.com/lanak1301/scribble.git
heroku link https://thawing-bayou-1750.herokuapp.com/

**Comment by jshawl** [comment]
:+1: I left code comments here - https://github.com/lanak1301/scribble/compare/master...jshawl:feedback

When I sign up at the heroku url, it gives me the "We're sorry, something went wrong" message. 

Try viewing the logs with `heroku logs` or changing env to development to view error messages:

```
heroku config:set RAILS_ENV=development
```
