### ISSUE TITLE
can't link my repo

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/scribble#2]
I generated this project via rails on my local computer and pushed it to my personal account.  I don't know how to link it to this master repo (since it was generated "from scratch" via rails...).  At any rate I was unable to get it to work since adding the authentication this morning.  (It worked temporarily but I have since broken it and am completely lost.)  Here is the link to my version (called Blog1.)  I am completely lost with rails and fear this may be my last week...

  https://github.com/tomBeach/blog1

  comfortLevel: 0
  completeness: 1

**Comment by adambray** [comment]
Hey Tom,

Let's set aside some time tomorrow morning during our Project 2 meeting to review your HW. After looking over your code, it looks like you were really close. (I only had to make a one line change to get your auth to work, for example).

-Adam
