### ISSUE TITLE
scribbler blog

### ISSUE THREAD

**Issue by ghost** [ga-dc/scribble#20]
comfort:4
complete: 4

Adding comments on the post is working, but editing is not. 
I'd like to put editing comments feature so that I can manage the comments.

https://wdi-dc6-taewan-scribblr.herokuapp.com/

repo: https://github.com/ktw1222/scribblrhw

**Comment by jshawl** [comment]
Nice job on this assignment! I left comments in the code here - https://github.com/ktw1222/scribblrhw/commit/33610a5ebe98e62cd112fc561c5aeed6b0b2c435

:+1: It was cool to see that other students have commented on your posts!!

**Comment by ghost** [comment]
Thank you for the comments!
