### ISSUE TITLE
Scribble HW Michael Holzheimer

### ISSUE THREAD

**Issue by alpha2262** [ga-dc/scribble#200]
https://github.com/alpha2262/scribble

Completeness: 4
Comfort: 3 (generally makes sense, just need to keep doing reps of rails creations)

**Comment by jshawl** [comment]
👍 nice!

from comments_controller:

``` rb
def create
    @post = Post.find(params[:post_id])
    @comment = Post.comments.create!(comment_params)
    #          ^^ should be @post
    redirect_to posts_path
end
```

Let me know if you'd like more specific feedback on this application - otherwise looks great!
