### ISSUE TITLE
HW::Masatoshi Nishiguchi

### ISSUE THREAD

**Issue by mnishiguchi** [ga-dc/scribble#204]
[Demo](https://mnishiguchi-scribble.herokuapp.com/)
[Repo](https://github.com/mnishiguchi/scribble)

``` yaml
comfortable: 5
complete:    5
```

I used Devise gem. I ran out of time for adding tags and testing.

**Comment by jshawl** [comment]
👍 Excellent!!!! Great to see you implemented devise and took a stab at tagging functionality
