### ISSUE TITLE
Week 6 HW 

### ISSUE THREAD

**Issue by SeanTay** [ga-dc/scribble#207]
https://github.com/SeanTay/scribble

Comfort Level 3/5
Completeness 2/5

I couldn't get my comments to link with the post ID. I didn't nest the routes that could the reason but I thought you can do it without nesting.

**Comment by nolds9** [comment]
👍 If you submit this as a pull request I can leave more detailed feedback. Going to go ahead and mark as complete, but let me know if you have any more questions
