### ISSUE TITLE
Erica Andersen's Scribble App

### ISSUE THREAD

**Issue by ericacomfort** [ga-dc/scribble#21]
## Scribble

**Heroku:** https://stormy-eyrie-6797.herokuapp.com/
**GitHub Repo:** https://github.com/andersenek/scribble

Comfort: 4/5
Completeness: 5/5

Concerns: I'm happy with most of the functionality and style of my Scribble App. If I had more time I would set conditions for posts/comments. A user should only be able to edit/delete a post/comment that they wrote. This was an excellent project to practice Rails with though and I definitely enjoyed it!

**Comment by adambray** [comment]
Please see my PR on your personal repo for feedback!
