### ISSUE TITLE
Julia Scribble HW

### ISSUE THREAD

**Issue by jschultz21** [ga-dc/scribble#210]
Comfort: 3
Complete: 4 (line 27 of my posts show page breaks everything, but without it everything works except the functionality to edit comments).

questions:
1. It seems my do loop on the post show page is running even when there are no comments, hence why the delete comment link appears regardless of whether the post has any comments or not. Does Ruby run through the do loop once by default? I tried fixing with an "if comments.length >0" loop but that didn't solve the problem.
2. why isn't line 27 of my posts show page working? this is the error I would get: "No route matches {:action=>"edit", :controller=>"comments", :id=>nil, :post_id=>"2"} missing required keys: [:id]" 

this is my comments controller: 

def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

```
if @comment.update(comments_params)
  redirect_to post_path(@post)
else
  render 'edit'
end
```

https://github.com/jschultz21/scribbleHW

**Comment by nolds9** [comment]
This throughs an error:
https://github.com/jschultz21/scribbleHW/blob/julia_solution/app/views/posts/show.html.erb#L28

because `comment` is no longer defined! Move it up so its inside the `each` loop

**Comment by nolds9** [comment]
Also same applies for https://github.com/jschultz21/scribbleHW/blob/julia_solution/app/views/posts/show.html.erb#L30

**Comment by nolds9** [comment]
👍 marked as complete
