### ISSUE TITLE
Scribble Blog

### ISSUE THREAD

**Issue by lscottcook** [ga-dc/scribble#23]
Comfort level:   3- thanks to poor committing practices I had to redo this assignment from scratch several times when I hit an error that I could not resolve that seemed to be based on how I set everything up.  

Completeness:  3-  i was able to add comments but somehow I did something and it is no longer working.  In some instances I had trouble  with "link_to" so I used `<href a>`.  I am glad that I had a chance to play around with the CSS because I was not sure how I could add tags on the views pages.  

Link to Heroku https://scribble-blog-lisa.herokuapp.com/

Here's the link to my repo. It does not completely match what is on Heroku. I think I committed and pushed something to Heroku that was not committed and used to GitHub but now the version on my laptop is not working correctly so I can't push it.  I do not completely understand master branch and and Heroku branch.  I tried to set up a workflow using branches on this project but I did not stick to it.  On the bright side I successfully merged  2 branches without any errors (small win).

**Comment by RobertAKARobin** [comment]
Oh, dear. I hope you didn't use `<href a>`. It's `<a href>`!

I love your `seeds.rb`

Your code looks great: very clean and easy-to-read.

Nicely done, Lisa!
