### ISSUE TITLE
Ficke Scribble

### ISSUE THREAD

**Issue by mattficke** [ga-dc/scribble#25]
Comfort: 4
Completeness: 4

Basic functionality all works, still working on adding image handling, better design, other complications, etc.

https://github.com/mattficke/scribble
https://ficke-scribbler.herokuapp.com/

**Comment by andrewsunglaekim** [comment]
I really like your callbacks in your posts and application controllers. I was wondering why you would want to skip before an edit, update and destroy. Great job overall! :+1:
