### ISSUE TITLE
jsm scribble

### ISSUE THREAD

**Issue by jsm13** [ga-dc/scribble#30]
github: https://github.com/jmas13/scribble
heroku: https://intense-crag-2576.herokuapp.com/

comfort: 4
completeness: 4

Got things working generally. Could spend a long time cleaning up --
in particular:
- views have way too much logic in them 
- controllers could use helper functions

**Comment by jshawl** [comment]
:+1: Excellent job auto-associating the user name with the new post! I also like the restricted functionality when the user is not logged in. 

I left code comments here - https://github.com/jmas13/scribble/compare/master...jshawl:feedback

Can you think of a way to auto sign-in users after they sign up?
