### ISSUE TITLE
Scribble Diary

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/scribble#34]
Comfort: 4
Completeness: 4.5

https://kg-scribble.herokuapp.com/sign_in
https://github.com/kristingreenslit/scribble

The app is fully functional except that when a comment is created it successfully saves to the db but does appear next to the corresponding post. Given more time I would spend time debugging the issue. It appears I need to reference the comments in the model for posts.

Some other future edits:
(1) View any blog post without requiring a user to log in
(2) Require all form fields in posts and comments to be filled out correctly before data is saved to the db
(3) Add more CSS to enhance the user experience

**Comment by andrewsunglaekim** [comment]
Looks great kristin! I looked at your code and tried to sniff out the problem. The only thing i could see was  that you called `.all` on top of the `.comments` Try getting rid of that all and it may fix your situation. Good job overall :+1:
