### ISSUE TITLE
Ksenia's Shitty Blog

### ISSUE THREAD

**Issue by kscoulter** [ga-dc/scribble#36]
comfort: 1.5
completeness: 3

https://ksenia-scribbles-rails.herokuapp.com/

**Comment by RobertAKARobin** [comment]
-100 points for this issue's title.

Impressed you modified the `authenticate` method!

Got all excited when I saw you'd made a helper for Posts. Sad panda that it was empty. :(

Clear evidence of you testing and debugging in your code. Nice!
