### ISSUE TITLE
Sinatra on Rails

### ISSUE THREAD

**Issue by jkoul** [ga-dc/scribble#45]
Heroku Deployment: http://sinatra-on-rails.herokuapp.com/
Github Repo: https://github.com/jkoul/scribble

Comfort: 4
Completeness: 4.5

Clearly, I deviated from the "Scribble" model completely, instead drawing inspiration from our development beyond Sinatra as an MVC framework and producing a tribute to Frank Sinatra. I feel pretty strong regarding  most the pieces we've learned, but am still struggling CSS and am weak on some of the particulars related to working with helpers.

**Comment by jshawl** [comment]
I LOVE the deviation! Your Ditties application is awesome!! :+1: :star: :star2: I will leave code comments here - https://github.com/ga-dc/scribble/compare/master...jkoul:master

**Comment by jshawl** [comment]
sorry code comments here https://github.com/ga-dc/scribble/pull/54
