### ISSUE TITLE
Scribble

### ISSUE THREAD

**Issue by ghost** [ga-dc/scribble#47]
Comfort:4
Complete:4.5

https://yvonne-scribble.herokuapp.com/

I learned a lot building this app! However,I ran out of time to add User Authentication. Also, Heroku changed my font after uploading it ahhh.

**Comment by RobertAKARobin** [comment]
Sorry about the font! You're not the only one to have that trouble. Instead of `http://fonts.google.com`, try just writing `//fonts.google.com`.

Is your code on Github anywhere?
