### ISSUE TITLE
Scribble

### ISSUE THREAD

**Issue by ghost** [ga-dc/scribble#49]
Comfort: 3.5
Completeness: 3.5

I learned a lot from working on this project. I think that was more helpful to me to work on this project over the course of the week and to implement everything we learned this week into one assignment than it is to complete individual homework assignments each night. Implementing many lessons into one assignment helped me see how the pieces fit together. It also seems like this style of hw will prepare us better for our projects and is more similar to what we'll be doing post-WDI.

There are some aspects of this project that I was not able to complete in time, but I would like to come back to this project and finish it later. It was really helpful to get to continue working on this on Friday in place of the lab. 

https://github.com/leighvarley/scribble

https://leigh-scribbler.herokuapp.com/

**Comment by RobertAKARobin** [comment]
I'm really glad it was helpful. Thanks for taking the time to write out your thoughts!

I like this color scheme. Bummer the Google Fonts didn't work.

I'm having trouble finding things to comment on. Your code is really consistent and well-written. Nice job!
