### ISSUE TITLE
Jeff Scribble

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/scribble#51]
Comfort: 5
Completeness: ~5
 https://jeff-scribble-wdi.herokuapp.com

**Comment by jshawl** [comment]
:+1: The deployed app looks awesome!!! I opened a pull request so I could comment on the code here:

https://github.com/ga-dc/scribble/pull/53

There are lots of things in your code that we did not cover in class. Good for you for taking initiative and building an awesome app!!!! :star: :star2:
