### ISSUE TITLE
Cameron's Scribble Submission

### ISSUE THREAD

**Issue by ghost** [ga-dc/scribble#8]
Link to repo: https://github.com/cameronfry11/Scribble/tree/cameron_solution

Link to deployed site (Also in ReadMe): https://thebombscribble.herokuapp.com

comfort: 3.5/5

completeness: 4/5

I still had styling left to do to contain the paragraph elements and comments when they are added to the page. I wanted to try the lab to hit on some of the hard skill concepts from the week and to get some repetition practice in with setting up a rails app. I'll come back to scribble and update when I get some extra time.

**Comment by andrewsunglaekim** [comment]
Great job on your homework! not too terribly worried about the styles. Getting all of the other functionality working is more important. :+1:  Maybe start to think about how you would refine the user interface even before the styles
