### ISSUE TITLE
Davis Solution

### ISSUE THREAD

**Issue by ghost** [ga-dc/scribble#85]
completion 4/5
comfort 3/5

Adds RESTful nested routes, and some use of helpers. Will go through and try to use helpers more consistently. 

https://mahartney-scribble.herokuapp.com/
https://github.com/Mahartney/scribble/tree/davis_solution

**Comment by jshawl** [comment]
:+1: code feedback coming in the next one!

**Comment by jshawl** [comment]
@Mahartney left comments on your last commit - https://github.com/Mahartney/scribble/commit/c57704e91a7dc99edee796eb6e17fc2ec0512e79 excellent job on this assignment!! Let me know if you'd like more feedback on other parts of the code, but looks great!!
