### ISSUE TITLE
Error with migration of db/seeds.rb in Scribble.

### ISSUE THREAD

**Issue by LauraWN** [ga-dc/scribble#9]
My postgres elephant is present. 
I run rake db:drop and then rake db:create... okay, I have my scribbler_db listed in postgres when I do \l.
I run rake db:migrate ... long pause when executed, but no long equal signs ======.
I run rake db:schema:dump... 
then I run rake db:seed and I get a long error, with this (I believe to be the important part):
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "comments" does not exist
LINE 1: SELECT "comments".\* FROM "comments
                                 ^ 
: SELECT "comments".\* FROM "comments"

Then after that if I run "remigrate" I get a long pause, but during that pause, I can see that the schema file is attempting to have some data written to it, because (I have Atom open) the schema file flashes the color that it is set to have when there are files with unsaved github changes. However, none of the changes stick. So I think there is an error with my seeds.rb file that is not enabling rails to run the smart stuff that it does to create the tables in the schema file.

**Comment by mattscilipoti** [comment]
Did you solve this?  If so, please give a brief explanation.

**Comment by mattscilipoti** [comment]
Either way - I assume you were able to continue without seed data.

**Comment by LauraWN** [comment]
yes, thanks! Sorry, I thought I closed it out.

**Comment by mattscilipoti** [comment]
You did close it.  You just didn't indicate what the solution was.  :)

**Comment by LauraWN** [comment]
Solution was to run $rails generate migration create_posts (and same then for other parts of the table).
