### ISSUE TITLE
Tory Burgett Homework Solution

### ISSUE THREAD

**Issue by toryburgett** [ga-dc/scribble#92]
Will add this as a pull request, but for now: https://github.com/toryburgett/scribble/tree/tory-solution

**Comment by toryburgett** [comment]
Still working on this, this is my current status: https://github.com/toryburgett/scribble
I plan to continue working on this this weekend

**Comment by amaseda** [comment]
Oops, looks like you forgot an "s" in your posts controller name...

``` rb
class PostController
   # ...
end
```

That's what's causing this error...

``` rb
Unable to autoload constant PostsController, expected /Users/adrianmaseda/GA/graded_hw/w06/scribble/tory/scribble/app/controllers/posts_controller.rb to define it
```

**Comment by amaseda** [comment]
When I try to create a post I get a `ForbiddenAttributesError`. You're going to need to use [strong params](https://github.com/ga-dc/curriculum/tree/master/05-mvc-with-rails/rails-views-and-controllers#strong-params) in your posts controller.

**Comment by amaseda** [comment]
Let me know if you have more recent code you want me to comment on. Happy to take a look!

:+1:
